<?php
global $shortcode_subpages;

if(!class_exists('PL_SC_Templates_List_Table')){
	require_once( PL_LIB_DIR . 'templates-table.php' );
}


$wp_list_table = new PL_SC_Templates_List_Table();
$wp_list_table->prepare_items();


PL_Router::load_builder_view('header.php');
?>
<div class="wrap pl-sc-wrap">
	<?php echo PL_Helper_Header::pl_subpages('placester_shortcodes', $shortcode_subpages, 'Shortcode Templates'); ?>

	<div id="pl_template_all">

		<p>
		These are the templates currently available for use with Placester shortcodes.
		Each template is associated with a specific shortcode and can be used to style and customize the output
		generated by the shortcode.
		</p>
		<p>You can select one of these templates for use with a shortcode by setting the shortcode's
		<code>context</code> attribute to the template's ID. For example:<br/>
		<code>[search_form context=twentyeleven]</code>
		</p>

		<?php $wp_list_table->views(); ?>

		<form id="posts-filter" action="edit.php" method="get">

		<?php $wp_list_table->display(); ?>

		</form>
	</div>

	<br class="clear" />
</div>
<?php
PL_Router::load_builder_view('footer.php');
